### ISSUE TITLE
Firefox bug: "#tabbrowser-tabpanels" color should honor currently selected theme background color

### ISSUE THREAD

**Issue by m-khvoinitsky** [m-khvoinitsky/dark-background-light-text-extension#132]
Part of the Firefox UI (which is white) is visible until [content window](https://developer.mozilla.org/en-US/docs/Web/API/Window) for tab is created. I used to fix this by [injecting custom stylesheet](https://github.com/m-khvoinitsky/dark-background-light-text-extension/blob/906ae49e5d3a8b04c449599065b1a8dcc88ee308/data/methods/global.css#L2) into Firefox main window. Now it's impossible.
This color should be the same as main background color of current theme, which, I suppose, is "Compact Dark" in case of most add-on users.
TODO: Firefox bugreport

**Comment by m-khvoinitsky** [comment]
Workaround:
add to `${firefoxprofile}/chrome/userChrome.css`
```css
.tabbrowser-tabbox > tabpanels > notificationbox {
    background-color: #000000 !important;
}
```
TODO: use color from theme
