### ISSUE TITLE
Fullscreen videos which doesn't fit screen should have black placeholders, not configured background color

### ISSUE THREAD

**Issue by m-khvoinitsky** [m-khvoinitsky/dark-background-light-text-extension#82]
```css
:fullscreen {
  background-color: black !important;
}
```
should fix an issue, however, `:fullscreen` selector doesn't work unless full-screen-api.unprefix.enabled is enabled which is not by default.
